<?xml version='1.0'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="train3">

 <xacro:property name="axel_offset" value="0.75" />
 <xacro:property name="axel_offset2" value="-0.75" />
 <xacro:property name="axel_z_offset" value="-0.3" />



 <xacro:property name="connector_x" value="1.5" />
 <xacro:property name="connector_y" value="0.25" />
 <xacro:property name="connector_z" value="0.25" />
 <xacro:property name="connector_mass" value="5" />

 <xacro:property name="body_x" value="1.5" />
 <xacro:property name="body_y" value="0.5" />
 <xacro:property name="body_z" value="0.5" />
 <xacro:property name="body_mass" value="30" />

 <xacro:property name="axle_x" value="0.2" />
 <!-- actual axle y distance -->
 <!--xacro:property name="axle_y" value="1.15052" /-->
 <xacro:property name="axle_y" value="1.15052" />
 <xacro:property name="axle_z" value="0.2" />
 <xacro:property name="axle_mass" value="15" />

 <xacro:property name="dummy_radius" value="0.25" />
  <xacro:property name="pi2" value="1.570796" />




 <xacro:macro name="wheel_gazebo_macro" params="reference">
 <gazebo reference="${reference}">
   <mu1>0.0</mu1>
   <mu2>0.5</mu2>
   <fdir1>1 0 0</fdir1>
   <!-- contact sensor -->
   <sensor type="contact" name="${reference}_contact_sensor">
     <update_rate>1000.0</update_rate>
     <always_on>true</always_on>
     <contact>
       <collision>${reference}_collision</collision>
     </contact>
     <plugin name="lside_bumper_plugin" filename="libgazebo_ros_bumper.so">
       <bumperTopicName>bumper_${reference}</bumperTopicName>
       <frameName>World</frameName>
      </plugin>
   </sensor>
 </gazebo>
 </xacro:macro>



  <xacro:macro name="wheel_macro" params="name model">
    <link name="${name}">
     <inertial>
      <mass value="7.5"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.49" ixy="0" ixz="0" iyy="0.49" iyz="0" izz="0.49"/>
     </inertial>
     <collision>
       <origin xyz="0 0 0" rpy="0 ${pi2} ${pi2}"/>
       <laser_retro>0</laser_retro>
       <max_contacts>10</max_contacts>
       <pose >0 0 0 0 0 0</pose>
       <geometry>
         <cylinder length="0.45" radius="0.28"/>
       </geometry>
     </collision>
     <visual name="visual">
      <origin rpy="0 ${pi2} ${pi2}" xyz="0 0 0"/>
      <geometry>
       <!--mesh filename="package://ros_robotics/meshes/${model}" scale="1 1 1"/-->
       <cylinder length="0.45" radius="0.28"/>
      </geometry>
      <material name="silver">
       <color rgba="0.75 0.75 0.75 1"/>
      </material>
     </visual>
    </link>
    <xacro:wheel_gazebo_macro reference="${name}"/>
  </xacro:macro>


 <xacro:macro name="pivot_joint_macro" params="xyz name parent child">
  <joint name="${name}" type="revolute">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <axis xyz="0  0  1"/>
   <limit effort="1000" lower="-0.003" upper="0.003" velocity="10"/>
   <dynamics damping="5" friction="1"/>
   <!--limit effort="-1" lower="-0.001" upper="0.001" velocity="-1"/-->
  </joint>
  <xacro:trans_macro name="${name}"/>
 </xacro:macro>

 <xacro:macro name="pivot_joint_roll_macro" params="xyz name parent child">
  <joint name="${name}" type="revolute">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <axis xyz="1  0  0"/>
   <limit effort="1000" lower="-0.1" upper="0.1" velocity="5"/>
   <dynamics damping="20" friction="0"/>
   <!--limit effort="-1" lower="-0.001" upper="0.001" velocity="-1"/-->
  </joint>
 </xacro:macro>

 <xacro:macro name="fixed_pivot_joint_roll_macro" params="xyz name parent child">
  <joint name="${name}" type="revolute">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <axis xyz="1  0  0"/>
   <limit effort="-1" lower="-0.001" upper="0.001" velocity="-1"/>
  </joint>
 </xacro:macro>

 <xacro:macro name="fixed_pivot_joint_macro" params="xyz name parent child">
  <joint name="${name}" type="revolute">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <axis xyz="0  0  1"/>
   <limit effort="-1" lower="-0.001" upper="0.001" velocity="-1"/>
   <!--limit effort="-1" lower="-0.001" upper="0.001" velocity="-1"/-->
  </joint>
  <xacro:trans_macro name="${name}"/>
 </xacro:macro>

<xacro:macro name="body_macro" params="xyz name">
 <link name="${name}">
  <inertial>
   <origin xyz="${xyz}"/>
   <mass value="${body_mass}"/>
   <inertia ixx="${(1/12)*body_mass*(pow(body_z,2) + pow(body_y,2))}" ixy="0" ixz="0" iyy="${(1/12)*body_mass*(pow(body_z,2) + pow(body_x,2))}" iyz="0" izz="${(1/12)*body_mass*(pow(body_x,2) + pow(body_y,2))}"/>
  </inertial>
  <!--collision name="collision">
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <geometry>
     <box size="${body_x} ${body_y} ${body_z}" />
   </geometry>
  </collision-->
  <visual name="visual">
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <geometry>
     <box size="${body_x} 0.5 0.5" />
   </geometry>
   <material name="silver">
    <color rgba="0.75 0.75 0.75 1"/>
   </material>
  </visual>
  </link>
 </xacro:macro>

 <xacro:macro name="trans_macro" params="name">
  <transmission name="simple_trans">
   <type>transmission_interface/SimpleTransmission</type>
   <joint name="${name}">
     <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
   </joint>
   <actuator name="motor_${name}">
     <mechanicalReduction>1</mechanicalReduction>
   </actuator>
  </transmission>
 </xacro:macro>

<xacro:macro name="axle_macro" params="xyz name">
 <link name="${name}">
  <inertial>
   <mass value="${axle_mass}"/>
   <origin rpy="0  0  0" xyz="0  0  0"/>
   <inertia ixx="${(1/12)*axle_mass*(pow(axle_z,2) + pow(axle_y,2))}" ixy="0" ixz="0" iyy="${(1/12)*axle_mass*(pow(axle_z,2) + pow(axle_x,2))}" iyz="0" izz="${(1/12)*axle_mass*(pow(axle_x,2) + pow(axle_y,2))}"/>
  </inertial>
  <!--collision name="collision">
   <origin rpy="0  0  0" xyz="0    0   0"/>
   <geometry>
    <mesh filename="package://ros_robotics/meshes/Front_Axle.STL" scale="1.0 1.0 1.0"/>
   </geometry>
  </collision-->
  <visual name="visual">
   <origin rpy="0  0  0" xyz="0 0 0"/>
   <geometry>
    <!--mesh filename="package://ros_robotics/meshes/Front_Axle.STL" scale="1 1 1"/-->
	<box size="${axle_x} ${axle_y} ${axle_z}" />
   </geometry>
   <material name="silver">
    <color rgba="0.75 0.75 0.75 1"/>
   </material>
  </visual>
 </link>
</xacro:macro>



<xacro:macro name="joint_wheel_macro" params="xyz name parent child">
 <joint name="${name}" type="revolute">
  <parent link="${parent}"/>
  <child link="${child}"/>
  <origin rpy="0    0    0" xyz="${xyz}"/>
  <axis xyz="0  1  0"/>
  <dynamics damping="0" friction="0"/>
  <limit effort="200" lower="-1e+16" upper="1e+16" velocity="20"/>
 </joint>
 <xacro:trans_macro name="${name}"/>
	
</xacro:macro>


<xacro:macro name="body_joint_macro" params="xyz axis name parent child">
  <joint name="${name}" type="revolute">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <axis xyz="${axis}"/>
   <!--limit effort="-1" lower="-1000" upper="1000" velocity="-1"/-->
   <dynamics damping="1" friction="1"/>
   <limit effort="1000" lower="-0.3" upper="0.3" velocity="10"/>
   <!--limit effort="1000" lower="-0.001" upper="0.001" velocity="10"/-->
  </joint>
  <xacro:trans_macro name="${name}"/>
</xacro:macro>


 <xacro:macro name="prismatic_joint_macro" params="xyz name parent child">
  <joint name="${name}" type="prismatic">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <axis xyz="1 0 0"/>
   <!-- upper limit allows contraction, lower limit allows elongation -->
   <!--limit effort="1000" lower="-0.25" upper="0.25" velocity="0.05"/-->
   <limit effort="1000" lower="-0.3" upper="0.3" velocity="10"/>
   <dynamics damping="1" friction="1"/>
  </joint>
  <xacro:trans_macro name="${name}"/>
    <gazebo reference="${name}">
    <provideFeedback>true</provideFeedback>
  </gazebo>
  <!-- The ft_sensor plugin -->  
  <gazebo>
    <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
        <updateRate>500.0</updateRate>
        <topicName>sensor_${name}</topicName>
        <jointName>${name}</jointName>
    </plugin>
  </gazebo>
</xacro:macro>

 <xacro:macro name="sensor_joint_macro" params="xyz name parent child">
  <joint name="${name}" type="revolute">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <axis xyz="1 0 0"/>
   <!-- upper limit allows contraction, lower limit allows elongation -->
   <!--limit effort="1000" lower="-0.25" upper="0.25" velocity="0.05"/-->
   <limit effort="1000" lower="-0.3" upper="0.3" velocity="10"/>
   <dynamics damping="1" friction="1"/>
  </joint>
  <xacro:trans_macro name="${name}"/>
    <gazebo reference="${name}">
    <provideFeedback>true</provideFeedback>
  </gazebo>
  <!-- The ft_sensor plugin -->  
  <gazebo>
    <plugin name="ft_sensor" filename="libgazebo_ros_ft_sensor.so">
        <updateRate>500.0</updateRate>
        <topicName>sensor_${name}</topicName>
        <jointName>${name}</jointName>
    </plugin>
  </gazebo>
</xacro:macro>


 <xacro:macro name="fixed_joint_macro" params="xyz name parent child limit">
  <joint name="${name}" type="fixed">
   <parent link="${parent}"/>
   <child link="${child}"/>
   <origin rpy="0 0 0" xyz="${xyz}"/>
   </joint>
</xacro:macro>

<xacro:macro name="dummy_link_macro" params="xyz name radius">
 <link name="${name}">
  <inertial>
   <mass value="0.2"/>
   <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
  </inertial>
  <visual name="visual">
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <geometry>
     <sphere radius="${radius}"/>
   </geometry>
   <material name="silver">
    <color rgba="0.75 0.75 0.75 1"/>
   </material>
  </visual>
  </link>
 </xacro:macro>

<xacro:macro name="connector_link_macro" params="xyz name">
 <link name="${name}">
  <inertial>
   <mass value="${connector_mass}"/>
   <inertia ixx="${(1/12)*connector_mass*(pow(connector_z,2) + pow(connector_y,2))}" ixy="0" ixz="0" iyy="${(1/12)*connector_mass*(pow(connector_z,2) + pow(connector_x,2))}" iyz="0" izz="${(1/12)*connector_mass*(pow(connector_x,2) + pow(connector_y,2))}"/>
  </inertial>
  <visual name="visual">
   <origin rpy="0 0 0" xyz="${xyz}"/>
   <geometry>
     <box size="${connector_x} ${connector_y} ${connector_z}" />
   </geometry>
   <material name="silver">
    <color rgba="0.75 0.75 0.75 1"/>
   </material>
  </visual>
  </link>
 </xacro:macro>


<!-- connector macro with prismatic joints -->
<xacro:macro name="connector_macro" params="parent child number">

	<xacro:body_joint_macro name="body_joint_${number}_z" parent="${parent}" child="dummy_${number}_1" xyz="${-body_x/2} 0 0" axis="0 0 1"/>
	<xacro:dummy_link_macro name="dummy_${number}_1" xyz="0 0 0" radius="${dummy_radius}"/>
	<xacro:body_joint_macro name="body_joint_${number}_y" parent="dummy_${number}_1" child="dummy_${number}_2" xyz="0 0 0" axis="0 1 0"/>
	<xacro:dummy_link_macro name="dummy_${number}_2" xyz="0 0 0" radius="${dummy_radius}"/>
	<xacro:body_joint_macro name="body_joint_${number}_x" parent="dummy_${number}_2" child="dummy_${number}_3" xyz="0 0 0" axis="1 0 0"/>
	<xacro:dummy_link_macro name="dummy_${number}_3" xyz="0 0 0" radius="${dummy_radius}"/>


	<xacro:prismatic_joint_macro name="prismatic_joint_${number}" parent="dummy_${number}_3" child="connector_${number}" xyz="${-connector_x/2} 0 0"/>
	<xacro:connector_link_macro name="connector_${number}" xyz="0 0 0"/>


	<xacro:body_joint_macro name="body_joint_${number}2_y" parent="connector_${number}" child="dummy_${number}_4" xyz="${-connector_x/2} 0 0" axis="0 1 0"/>
	<xacro:dummy_link_macro name="dummy_${number}_4" xyz="0 0 0" radius="${dummy_radius}"/>
	<xacro:body_joint_macro name="body_joint_${number}2_z" parent="dummy_${number}_4" child="dummy_${number}_5" xyz="0 0 0" axis="0 0 1"/>
	<xacro:dummy_link_macro name="dummy_${number}_5" xyz="0 0 0" radius="${dummy_radius}"/>
	<xacro:fixed_joint_macro name="fixed_joint_${number}_1" parent="dummy_${number}_5" child="${child}" xyz="${-body_x/2} 0 0" limit="0.0001"/>
</xacro:macro>  


<!-- connector macro no joints
<xacro:macro name="connector_macro" params="parent child number">

	<xacro:body_joint_macro name="body_joint_${number}_z" parent="${parent}" child="dummy_${number}_1" xyz="${-body_x/2} 0 0" axis="0 0 1"/>
	<xacro:dummy_link_macro name="dummy_${number}_1" xyz="0 0 0" radius="${dummy_radius}"/>
	<xacro:body_joint_macro name="body_joint_${number}_y" parent="dummy_${number}_1" child="dummy_${number}_2" xyz="0 0 0" axis="0 1 0"/>
	<xacro:dummy_link_macro name="dummy_${number}_2" xyz="0 0 0" radius="${dummy_radius}"/>



	<xacro:sensor_joint_macro name="prismatic_joint_${number}" parent="dummy_${number}_2" child="connector_${number}" xyz="${-connector_x/2} 0 0"/>
	<xacro:connector_link_macro name="connector_${number}" xyz="0 0 0"/>


	<xacro:body_joint_macro name="body_joint_${number}2_y" parent="connector_${number}" child="dummy_${number}_4" xyz="${-connector_x/2} 0 0" axis="0 1 0"/>
	<xacro:dummy_link_macro name="dummy_${number}_4" xyz="0 0 0" radius="${dummy_radius}"/>
	<xacro:body_joint_macro name="body_joint_${number}2_z" parent="dummy_${number}_4" child="dummy_${number}_5" xyz="0 0 0" axis="0 0 1"/>
	<xacro:dummy_link_macro name="dummy_${number}_5" xyz="0 0 0" radius="${dummy_radius}"/>
	<xacro:body_joint_macro name="body_joint_${number}2_x" parent="dummy_${number}_5" child="${child}" xyz="${-body_x/2} 0 0" axis="1 0 0"/>
</xacro:macro>
-->


<!-- Segment Macro --> 
<xacro:macro name="segment_macro" params="number">
	<xacro:body_macro name="body_${number}" xyz="0 0 0"/>	

	<xacro:pivot_joint_macro name="pivot_joint_${number}_1" parent="body_${number}" child="pivot_dummy_${number}_1" xyz="${axel_offset} 0 ${axel_z_offset}"/>
	<xacro:dummy_link_macro name="pivot_dummy_${number}_1" xyz="0 0 0" radius="0.1"/>
	<xacro:pivot_joint_roll_macro name="pivot_joint_roll_${number}_1" parent="pivot_dummy_${number}_1" child="axle_${number}_1" xyz="0 0 0"/>
	<xacro:axle_macro name="axle_${number}_1" xyz="0 0 0"/>

	<xacro:joint_wheel_macro xyz="0  ${axle_y/2} 0" name="joint_wheel_${number}_1_1" parent="axle_${number}_1" child="wheel_${number}_1_1"/>
	<xacro:joint_wheel_macro xyz="0  -${axle_y/2} 0" name="joint_wheel_${number}_1_2" parent="axle_${number}_1" child="wheel_${number}_1_2"/>
	<xacro:wheel_macro name="wheel_${number}_1_1" model="frostyboy_wheel.STL"/>
	<xacro:wheel_macro name="wheel_${number}_1_2" model="frostyboy_wheel.STL"/>


	<xacro:pivot_joint_macro name="pivot_joint_${number}_2" parent="body_${number}" child="pivot_dummy_${number}_2" xyz="${axel_offset2} 0 ${axel_z_offset}"/>
	<xacro:dummy_link_macro name="pivot_dummy_${number}_2" xyz="0 0 0" radius="0.1"/>
	<xacro:fixed_pivot_joint_roll_macro name="pivot_joint_roll_${number}_2" parent="pivot_dummy_${number}_2" child="axle_${number}_2" xyz="0 0 0"/>
	<xacro:axle_macro name="axle_${number}_2" xyz="0 0 0"/>

	<xacro:joint_wheel_macro xyz="0  ${axle_y/2} 0" name="joint_wheel_${number}_2_1" parent="axle_${number}_2" child="wheel_${number}_2_1"/>
	<xacro:joint_wheel_macro xyz="0  -${axle_y/2} 0" name="joint_wheel_${number}_2_2" parent="axle_${number}_2" child="wheel_${number}_2_2"/>
	<xacro:wheel_macro name="wheel_${number}_2_1" model="frostyboy_wheel.STL"/>
	<xacro:wheel_macro name="wheel_${number}_2_2" model="frostyboy_wheel.STL"/>
</xacro:macro>



<!-- The Actual Vehicle -->
<xacro:segment_macro number="1"/>

<xacro:connector_macro parent="body_1" child="body_2" number="1"  />
<xacro:segment_macro number="2"/>

<xacro:connector_macro parent="body_2" child="body_3" number="2"  />
<xacro:segment_macro number="3"/>

<xacro:connector_macro parent="body_3" child="body_4" number="3"  />
<xacro:segment_macro number="4"/>

<xacro:connector_macro parent="body_4" child="body_5" number="4"  />
<xacro:segment_macro number="5"/>

<xacro:connector_macro parent="body_5" child="body_6" number="5"  />
<xacro:segment_macro number="6"/>
<!--
<xacro:connector_macro parent="body_6" child="body_7" number="6"  />
<xacro:segment_macro number="7"/>

<xacro:connector_macro parent="body_7" child="body_8" number="7"  />
<xacro:segment_macro number="8"/>

<xacro:connector_macro parent="body_8" child="body_9" number="8"  />
<xacro:segment_macro number="9"/>

<xacro:connector_macro parent="body_9" child="body_10" number="9"  />
<xacro:segment_macro number="10"/>

-->





<!-- front and back dummy links (primarily for visual)
<xacro:body_joint_macro name="dummy_joint_front" parent="body_1" child="dummy_link_front" xyz="${+body_x/2} 0 0" axis="0 0 1"/>
<xacro:dummy_link_macro name="dummy_link_front" xyz="0 0 0" radius="${dummy_radius}"/>

<xacro:body_joint_macro name="dummy_joint_back" parent="body_1" child="dummy_link_back" xyz="${-body_x/2} 0 0" axis="0 0 1"/>
<xacro:dummy_link_macro name="dummy_link_back" xyz="0 0 0" radius="${dummy_radius}"/>
 -->

<!-- run this in order to check the URDF without launching gazebo -->
<!-- https://answers.ros.org/question/258420/ball-joint-in-urdf/ -->
<!-- "check_urdf <(xacro inorder train5.urdf.xacro)" but put two dashes before inorder-->

<gazebo>
  <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
   <robotNamespace>/dd_robot</robotNamespace>
   <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
   <legacyModeNS>true</legacyModeNS>
  </plugin>
</gazebo>

<gazebo>
  <!--plugin name="hello_world" filename="libhello_world.so"/-->
  <plugin name="model_push" filename="./libmodel_push.so"/>
</gazebo>


</robot>
