dd_robot:
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 1500
 joint_wheel_1_1_1_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_1_1_1
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_1_1_2_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_1_1_2
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_1_2_1_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_1_2_1
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_1_2_2_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_1_2_2
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_2_1_1_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_2_1_1
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_2_1_2_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_2_1_2
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_2_2_1_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_2_2_1
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_2_2_2_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_2_2_2
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_3_1_1_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_3_1_1
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_3_1_2_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_3_1_2
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_3_2_1_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_3_2_1
  pid: {p: 0.0, i: 0.00, d: 0.0}
 joint_wheel_3_2_2_controller:
  type: effort_controllers/JointEffortController
  joint: joint_wheel_3_2_2
  pid: {p: 0.0, i: 0.00, d: 0.0}
# body_joint_1_z_controller:
#  type: effort_controllers/JointEffortController
#  joint: body_joint_1_z
#  pid: {p: 0.0, i: 0.00, d: 0.0}
# body_joint_2_z_controller:
#  type: effort_controllers/JointEffortController
#  joint: body_joint_2_z
#  pid: {p: 0.0, i: 0.00, d: 0.0}
# pivot_joint_1_1_controller:
#  type: effort_controllers/JointEffortController
#  joint: pivot_joint_1_1
#  pid: {p: 0.0, i: 0.00, d: 0.0}
# pivot_joint_1_2_controller:
#  type: effort_controllers/JointEffortController
#  joint: pivot_joint_2_1
#  pid: {p: 0.0, i: 0.00, d: 0.0}
# pivot_joint_2_1_controller:
#  type: effort_controllers/JointEffortController
#  joint: pivot_joint_1_1
#  pid: {p: 0.0, i: 0.00, d: 0.0}
# pivot_joint_2_2_controller:
#  type: effort_controllers/JointEffortController
#  joint: pivot_joint_2_1
# pid: {p: 0.0, i: 0.00, d: 0.0}
# pivot_joint_3_1_controller:
# type: effort_controllers/JointEffortController
# joint: pivot_joint_1_1
#  pid: {p: 0.0, i: 0.00, d: 0.0}
# pivot_joint_3_2_controller:
#  type: effort_controllers/JointEffortController
# joint: pivot_joint_2_1
# pid: {p: 0.0, i: 0.00, d: 0.0}
